name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-qt
    
    - name: Run tests
      run: |
        pytest tests/
    
    - name: Build application
      run: |
        pip install pyinstaller
        pyinstaller --name="GS Browser" ^
                    --windowed ^
                    --icon=icons/chrome.ico ^
                    --add-data "icons;icons" ^
                    --add-data "config;config" ^
                    --add-data "homepage.html;." ^
                    --add-data "*.qss;." ^
                    gs_browser.py
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: gs-browser-build
        path: dist/GS Browser/ 